### ISSUE TITLE
ValueError: Required parameter public_ip not set

### ISSUE THREAD

**Issue by philbudne** [skymill/aws-ec2-assign-elastic-ip#28]
Command that worked under 0.7.1 fails under 8.0:

# /usr/local/bin/aws-ec2-assign-elastic-ip --region us-east-1 --valid-ips A.B.C.D
2018-07-18 15:44:17,610 - aws-ec2-assign-eip - INFO - Connected to AWS EC2 in us-east-1
Traceback (most recent call last):
  File "/usr/local/bin/aws-ec2-assign-elastic-ip", line 31, in <module>
    aws_ec2_assign_elastic_ip.main()
  File "/usr/local/lib/python2.7/dist-packages/aws_ec2_assign_elastic_ip/__init__.py", line 61, in main
    address = _get_unassociated_address()
  File "/usr/local/lib/python2.7/dist-packages/aws_ec2_assign_elastic_ip/__init__.py", line 137, in _get_unassociated_address
    eip = ec2_resource.ClassicAddress(address.get('AllocationId'))
  File "/usr/local/lib/python2.7/dist-packages/boto3/resources/factory.py", line 474, in create_resource
    client=self.meta.client)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/boto3/resources/base.py", line 119, in __init__
    'Required parameter {0} not set'.format(identifier))
ValueError: Required parameter public_ip not set

**Comment by sebdah** [comment]
0.8.0 has been reverted. I have released 0.8.1 which is essentially just a rollback. Sorry for the inconvenience!
