### ISSUE TITLE
aws-ec2-assign-elastic-ip is not assigning EIP's to the EC2 instances

### ISSUE THREAD

**Issue by OmPrasadReddy** [skymill/aws-ec2-assign-elastic-ip#41]
Hi,

aws-ec2-assign-elastic-ip has added as a part of boostrap scrip in auto scaling group but it was suddenly not assigning EIP's to the instances after launching. It would be great if you could let me know the resason?

#!/bin/bash
sudo yum install python34-pip  -y
sudo pip install aws-ec2-assign-elastic-ip
runuser -l ec2-user -c 'aws-ec2-assign-elastic-ip  --valid-ips   9.9.9.9'

**Comment by sebdah** [comment]
Best would be to try to run `aws-ec2-assign-elastic-ip` manually to see what the outcome would be. You could also try looking at the logs. But with the above information I can't know what is wrong unfortunately.

**Comment by OmPrasadReddy** [comment]
I see below error.

aws-ec2-assign-elastic-ip  --valid-ips 9.9.9.9
/usr/local/lib/python2.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.11) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Traceback (most recent call last):
  File "/usr/bin/aws-ec2-assign-elastic-ip", line 26, in <module>
    import aws_ec2_assign_elastic_ip
  File "/usr/lib/python2.7/dist-packages/aws_ec2_assign_elastic_ip/__init__.py", line 14, in <module>
    from ec2_metadata import ec2_metadata
  File "/usr/lib/python2.7/dist-packages/ec2_metadata.py", line 4, in <module>
    import requests
  File "/usr/local/lib/python2.7/site-packages/requests/__init__.py", line 112, in <module>
    from . import utils
  File "/usr/local/lib/python2.7/site-packages/requests/utils.py", line 26, in <module>
    from ._internal_utils import to_native_string
  File "/usr/local/lib/python2.7/site-packages/requests/_internal_utils.py", line 11, in <module>
    from .compat import is_py2, builtin_str, str
  File "/usr/local/lib/python2.7/site-packages/requests/compat.py", line 48, in <module>
    from urllib3.packages.ordered_dict import OrderedDict
ImportError: No module named ordered_dict

**Comment by OmPrasadReddy** [comment]
I have upgraded pip to pip3 as below 
sudo yum install python35
sudo yum install python35-pip
sudo python3 -m pip install aws-ec2-assign-elastic-ip

When i ran the command on the instance manually, seeing below message.

aws-ec2-assign-elastic-ip  --valid-ips 9.9.9.9

2020-10-25 10:17:52,995 - aws-ec2-assign-eip - INFO - Connected to AWS EC2 in us-east-1
2020-10-25 10:17:53,295 - aws-ec2-assign-eip - ERROR - No unassociated Elastic IP found!

The EIP is not associated to any instance. Any idea what could be the reason?

**Comment by OmPrasadReddy** [comment]
Thanks @sebdah. Fixed it by upgrading python version to 3.5. Hope it is useful for others whoever facing this error.

Steps: 
sudo yum install python35
sudo yum install python35-pip
sudo python3 -m pip install aws-ec2-assign-elastic-ip
aws-ec2-assign-elastic-ip --valid-ips 9.9.9.9
